package localization

func (s *Service) loadAssistantTranslations() {
	s.AddTranslations(LocaleEnglish, map[string]string{
		"assistant.home.header":                "Control center for your userbot and assistant.",
		"assistant.home.status_ready":          "🟢 Online & ready",
		"assistant.home.footer":                "<i>Assistant shell navigation and state are fully a2-native.</i>",
		"assistant.status.title":               "GoUltroid Assistant - Stats",
		"assistant.status.header":              "Assistant runtime health and transport information.",
		"assistant.status.operational":         "Online",
		"assistant.status.active":              "Active",
		"assistant.status.footer":              "<i>Refresh reads the latest runtime state without creating a new session.</i>",
		"assistant.field.bot":                  "Bot",
		"assistant.field.assistant":            "Assistant",
		"assistant.field.status":               "Status",
		"assistant.field.uptime":               "Uptime",
		"assistant.field.engine":               "Engine",
		"assistant.field.callbacks":            "Callbacks",
		"assistant.field.refreshes":            "Session refreshes",
		"assistant.button.settings":            "Settings ⚙️",
		"assistant.button.help":                "Hᴇʟᴘ 📚",
		"assistant.button.status":              "Sᴛᴀᴛs ✨",
		"assistant.button.refresh":             "Rᴇғʀᴇsʜ 🔄",
		"assistant.button.ping":                "Pɪɴɢ 🌋",
		"assistant.button.home":                "« Bᴀᴄᴋ",
		"assistant.button.language":            "Language 🌐",
		"assistant.button.previous":            "« Pʀᴇᴠɪᴏᴜs",
		"assistant.button.next":                "Nᴇxᴛ »",
		"assistant.button.open":                "Oᴘᴇɴ",
		"assistant.button.details":             "Dᴇᴛᴀɪʟs",
		"assistant.button.modules":             "« Bᴀᴄᴋ »",
		"assistant.button.commands":            "« Bᴀᴄᴋ",
		"assistant.language.title":             "List Of Available Languages.",
		"assistant.language.header":            "Choose the language used by the Assistant control interface.",
		"assistant.language.current":           "Current",
		"assistant.language.saved":             "Language preference saved.",
		"assistant.language.english":           "🇬🇧 English",
		"assistant.language.indonesian":        "🇮🇩 Bahasa Indonesia",
		"assistant.language.footer":            "<i>The selection is stored in the canonical ui:locale user setting.</i>",
		"assistant.public.header":              "Assistant endpoint is online.",
		"assistant.public.owner_only":          "<i>The interactive control shell is available only to its authorized owner.</i>",
		"assistant.help.title":                 "GoUltroid Help Menu",
		"assistant.help.header":                "Choose a module below.",
		"assistant.help.commands":              "Commands",
		"assistant.help.modules":               "Modules",
		"assistant.help.selected":              "Selected",
		"assistant.help.position":              "Position",
		"assistant.help.empty":                 "<i>No Assistant commands are currently registered.</i>",
		"assistant.help.footer":                "<i>Open the selected module, or move through the bounded module navigator.</i>",
		"assistant.help.module_header":         "Browse commands in this module.",
		"assistant.help.module_empty":          "<i>No commands are currently available in this module.</i>",
		"assistant.help.module_footer":         "<i>Open Details for usage, aliases, permissions, and execution constraints.</i>",
		"assistant.help.no_description":        "No command description is registered.",
		"assistant.help.usage":                 "Usage",
		"assistant.help.aliases":               "Aliases",
		"assistant.help.module":                "Module",
		"assistant.help.permission":            "Permission",
		"assistant.help.context":               "Context",
		"assistant.help.group_only":            "Group only",
		"assistant.help.private_only":          "Private only",
		"assistant.help.reply_required":        "Reply required",
		"assistant.help.cooldown":              "Cooldown",
		"assistant.help.timeout":               "Timeout",
		"assistant.help.resources":             "Resources",
		"assistant.help.execute":               "<i>Execute it with /%s.</i>",
		"assistant.settings.header":            "Choose from the below options -",
		"assistant.settings.categories":        "Categories",
		"assistant.settings.selected":          "Selected",
		"assistant.settings.position":          "Position",
		"assistant.settings.empty":             "<i>No settings are currently registered.</i>",
		"assistant.settings.footer":            "<i>Settings writes, resets, and free-form input are owned by the revision-fenced a2 flow.</i>",
		"assistant.settings.category_header":   "Browse effective values in this settings category.",
		"assistant.settings.settings":          "Settings",
		"assistant.settings.category_empty":    "<i>No settings are currently registered in this category.</i>",
		"assistant.settings.current":           "Current",
		"assistant.settings.key":               "Key",
		"assistant.settings.source":            "Source",
		"assistant.settings.type":              "Type",
		"assistant.settings.default":           "Default",
		"assistant.settings.widget":            "Widget",
		"assistant.settings.options":           "Options",
		"assistant.settings.range":             "Range",
		"assistant.settings.step":              "Step",
		"assistant.settings.result":            "Result",
		"assistant.settings.no_description":    "No description is registered for this setting.",
		"assistant.settings.inherited":         "Inherited/default",
		"assistant.settings.change":            "✏️ Change",
		"assistant.settings.decrease":          "➖ Decrease",
		"assistant.settings.increase":          "➕ Increase",
		"assistant.settings.reset":             "↩ Reset user override",
		"assistant.settings.category":          "« Category",
		"assistant.settings.freeform":          "<i>Free-form input uses the bounded a2 input session.</i>",
		"assistant.settings.detail_footer":     "<i>Mutation is bound to this stable setting identity and consumes the current session revision before persistence.</i>",
		"assistant.settings.input":             "Input",
		"assistant.settings.cancel":            "Cancel",
		"assistant.settings.expires":           "Expires",
		"assistant.settings.input_header":      "Send the new value as your next message.",
		"assistant.settings.input_prompt":      "Send the new value as your next message in this chat.",
		"assistant.settings.two_minutes":       "2 minutes",
		"assistant.settings.privacy":           "Privacy",
		"assistant.settings.privacy_text":      "Sensitive values are never echoed back in the Settings UI.",
		"assistant.settings.input_footer":      "<i>Only this actor/chat can satisfy the pending input claim. Other slash commands continue normally.</i>",
		"assistant.settings.cancel_input":      "❌ Cancel input",
		"assistant.settings.empty_value":       "<i>empty</i>",
		"assistant.settings.general":           "⚙️ General",
		"assistant.settings.security":          "🔒 Security",
		"assistant.settings.moderation":        "🛡 Moderation",
		"assistant.settings.automation":        "🤖 Automation",
		"assistant.settings.interface":         "🎨 Interface",
		"assistant.settings.advanced":          "🧰 Advanced",
		"assistant.settings.other":             "Other",
		"assistant.settings.chat_override":     "Chat override",
		"assistant.settings.user_override":     "User override",
		"assistant.settings.global_override":   "Global override",
		"assistant.settings.default_source":    "Default",
		"assistant.settings.locale_title":      "Assistant Language",
		"assistant.settings.locale_desc":       "Language used by the Assistant control interface",
		"assistant.inline.title":               "GoUltroid Userbot",
		"assistant.inline.active":              "Active",
		"assistant.inline.hint":                "Type <code>@bot help</code> to search feature commands or <code>@bot ping</code> for status.",
		"assistant.inline.search_help":         "• Help •",
		"assistant.inline.ping_status":         "•Pɪɴɢ•",
		"assistant.inline.description":         "Search feature commands and view runtime status",
		"assistant.inline.help_menu":           "« Bᴀᴄᴋ",
		"assistant.inline.status_title":        "GoUltroid Status",
		"assistant.inline.online_uptime":       "Online | Uptime %s",
		"assistant.inline.online":              "Online",
		"assistant.inline.no_description":      "No description",
		"assistant.inline.feature":             "Feature",
		"assistant.inline.command":             "Command",
		"assistant.inline.description_field":   "Description",
		"assistant.inline.search_more":         "Sᴇᴀʀᴄʜ Mᴏʀᴇ",
		"assistant.inline.no_match":            "No commands matched the current feature catalog.",
		"assistant.inline.catalog_unavailable": "Feature catalog is unavailable.",
		"assistant.inline.help_title":          "GoUltroid Help",
	})

	s.AddTranslations(LocaleIndonesian, map[string]string{
		"assistant.home.header":                "Pusat kontrol untuk userbot dan Assistant Anda.",
		"assistant.home.status_ready":          "🟢 Online & siap",
		"assistant.home.footer":                "<i>Navigasi dan state Assistant shell sepenuhnya native a2.</i>",
		"assistant.status.title":               "GoUltroid Assistant - Stats",
		"assistant.status.header":              "Kesehatan runtime Assistant dan informasi transport.",
		"assistant.status.operational":         "Online",
		"assistant.status.active":              "Aktif",
		"assistant.status.footer":              "<i>Refresh membaca state runtime terbaru tanpa membuat sesi baru.</i>",
		"assistant.field.bot":                  "Bot",
		"assistant.field.assistant":            "Assistant",
		"assistant.field.status":               "Status",
		"assistant.field.uptime":               "Waktu aktif",
		"assistant.field.engine":               "Engine",
		"assistant.field.callbacks":            "Callback",
		"assistant.field.refreshes":            "Refresh sesi",
		"assistant.button.settings":            "Pengaturan ⚙️",
		"assistant.button.help":                "Bantuan 📚",
		"assistant.button.status":              "Sᴛᴀᴛs ✨",
		"assistant.button.refresh":             "Rᴇғʀᴇsʜ 🔄",
		"assistant.button.ping":                "Pɪɴɢ 🌋",
		"assistant.button.home":                "« Kembali",
		"assistant.button.language":            "Bahasa 🌐",
		"assistant.button.previous":            "« Sebelumnya",
		"assistant.button.next":                "Berikutnya »",
		"assistant.button.open":                "Bᴜᴋᴀ",
		"assistant.button.details":             "Dᴇᴛᴀɪʟ",
		"assistant.button.modules":             "« Kembali »",
		"assistant.button.commands":            "« Kembali",
		"assistant.language.title":             "Daftar Bahasa Tersedia.",
		"assistant.language.header":            "Pilih bahasa yang digunakan antarmuka kontrol Assistant.",
		"assistant.language.current":           "Saat ini",
		"assistant.language.saved":             "Preferensi bahasa tersimpan.",
		"assistant.language.english":           "🇬🇧 English",
		"assistant.language.indonesian":        "🇮🇩 Bahasa Indonesia",
		"assistant.language.footer":            "<i>Pilihan disimpan pada setting user canonical ui:locale.</i>",
		"assistant.public.header":              "Endpoint Assistant sedang online.",
		"assistant.public.owner_only":          "<i>Shell kontrol interaktif hanya tersedia bagi owner yang berwenang.</i>",
		"assistant.help.title":                 "Menu Bantuan GoUltroid",
		"assistant.help.header":                "Pilih modul di bawah.",
		"assistant.help.commands":              "Perintah",
		"assistant.help.modules":               "Modul",
		"assistant.help.selected":              "Terpilih",
		"assistant.help.position":              "Posisi",
		"assistant.help.empty":                 "<i>Belum ada perintah Assistant yang terdaftar.</i>",
		"assistant.help.footer":                "<i>Buka modul terpilih atau pindah melalui navigator modul yang bounded.</i>",
		"assistant.help.module_header":         "Jelajahi perintah dalam modul ini.",
		"assistant.help.module_empty":          "<i>Tidak ada perintah yang tersedia dalam modul ini.</i>",
		"assistant.help.module_footer":         "<i>Buka Detail untuk penggunaan, alias, izin, dan batas eksekusi.</i>",
		"assistant.help.no_description":        "Tidak ada deskripsi perintah yang terdaftar.",
		"assistant.help.usage":                 "Penggunaan",
		"assistant.help.aliases":               "Alias",
		"assistant.help.module":                "Modul",
		"assistant.help.permission":            "Izin",
		"assistant.help.context":               "Konteks",
		"assistant.help.group_only":            "Hanya grup",
		"assistant.help.private_only":          "Hanya privat",
		"assistant.help.reply_required":        "Wajib reply",
		"assistant.help.cooldown":              "Cooldown",
		"assistant.help.timeout":               "Timeout",
		"assistant.help.resources":             "Resource",
		"assistant.help.execute":               "<i>Jalankan dengan /%s.</i>",
		"assistant.settings.header":            "Pilih dari opsi di bawah -",
		"assistant.settings.categories":        "Kategori",
		"assistant.settings.selected":          "Terpilih",
		"assistant.settings.position":          "Posisi",
		"assistant.settings.empty":             "<i>Belum ada pengaturan yang terdaftar.</i>",
		"assistant.settings.footer":            "<i>Write, reset, dan input bebas pengaturan dimiliki flow a2 dengan revision fence.</i>",
		"assistant.settings.category_header":   "Jelajahi nilai efektif dalam kategori pengaturan ini.",
		"assistant.settings.settings":          "Pengaturan",
		"assistant.settings.category_empty":    "<i>Tidak ada pengaturan yang terdaftar pada kategori ini.</i>",
		"assistant.settings.current":           "Saat ini",
		"assistant.settings.key":               "Key",
		"assistant.settings.source":            "Sumber",
		"assistant.settings.type":              "Tipe",
		"assistant.settings.default":           "Default",
		"assistant.settings.widget":            "Widget",
		"assistant.settings.options":           "Opsi",
		"assistant.settings.range":             "Rentang",
		"assistant.settings.step":              "Langkah",
		"assistant.settings.result":            "Hasil",
		"assistant.settings.no_description":    "Tidak ada deskripsi yang terdaftar untuk pengaturan ini.",
		"assistant.settings.inherited":         "Inherited/default",
		"assistant.settings.change":            "✏️ Ubah",
		"assistant.settings.decrease":          "➖ Kurangi",
		"assistant.settings.increase":          "➕ Tambah",
		"assistant.settings.reset":             "↩ Reset override user",
		"assistant.settings.category":          "« Kategori",
		"assistant.settings.freeform":          "<i>Input bebas menggunakan sesi input a2 yang bounded.</i>",
		"assistant.settings.detail_footer":     "<i>Mutasi terikat ke identitas setting stabil dan mengonsumsi revisi sesi saat ini sebelum persistence.</i>",
		"assistant.settings.input":             "Input",
		"assistant.settings.cancel":            "Batal",
		"assistant.settings.expires":           "Kedaluwarsa",
		"assistant.settings.input_header":      "Kirim nilai baru sebagai pesan berikutnya.",
		"assistant.settings.input_prompt":      "Kirim nilai baru sebagai pesan berikutnya di chat ini.",
		"assistant.settings.two_minutes":       "2 menit",
		"assistant.settings.privacy":           "Privasi",
		"assistant.settings.privacy_text":      "Nilai sensitif tidak pernah ditampilkan kembali di UI Pengaturan.",
		"assistant.settings.input_footer":      "<i>Hanya actor/chat ini yang dapat memenuhi klaim input aktif. Slash command lain tetap berjalan normal.</i>",
		"assistant.settings.cancel_input":      "❌ Batalkan input",
		"assistant.settings.empty_value":       "<i>kosong</i>",
		"assistant.settings.general":           "⚙️ Umum",
		"assistant.settings.security":          "🔒 Keamanan",
		"assistant.settings.moderation":        "🛡 Moderasi",
		"assistant.settings.automation":        "🤖 Otomasi",
		"assistant.settings.interface":         "🎨 Antarmuka",
		"assistant.settings.advanced":          "🧰 Lanjutan",
		"assistant.settings.other":             "Lainnya",
		"assistant.settings.chat_override":     "Override chat",
		"assistant.settings.user_override":     "Override user",
		"assistant.settings.global_override":   "Override global",
		"assistant.settings.default_source":    "Default",
		"assistant.settings.locale_title":      "Bahasa Assistant",
		"assistant.settings.locale_desc":       "Bahasa yang digunakan antarmuka kontrol Assistant",
		"assistant.inline.title":               "GoUltroid Userbot",
		"assistant.inline.active":              "Aktif",
		"assistant.inline.hint":                "Ketik <code>@bot help</code> untuk mencari perintah fitur atau <code>@bot ping</code> untuk status.",
		"assistant.inline.search_help":         "• Bantuan •",
		"assistant.inline.ping_status":         "•Pɪɴɢ•",
		"assistant.inline.description":         "Cari perintah fitur dan lihat status runtime",
		"assistant.inline.help_menu":           "« Kembali",
		"assistant.inline.status_title":        "Status GoUltroid",
		"assistant.inline.online_uptime":       "Online | Waktu aktif %s",
		"assistant.inline.online":              "Online",
		"assistant.inline.no_description":      "Tidak ada deskripsi",
		"assistant.inline.feature":             "Fitur",
		"assistant.inline.command":             "Perintah",
		"assistant.inline.description_field":   "Deskripsi",
		"assistant.inline.search_more":         "Cari Lagi",
		"assistant.inline.no_match":            "Tidak ada perintah yang cocok dengan katalog fitur saat ini.",
		"assistant.inline.catalog_unavailable": "Katalog fitur tidak tersedia.",
		"assistant.inline.help_title":          "Bantuan GoUltroid",
	})
}
