package localization

func (s *Service) loadCommonUXTranslations() {
	s.AddTranslations(LocaleEnglish, map[string]string{
		"ui.close":    "❌ Close",
		"ui.home":     "🏠 Home",
		"ui.back":     "🔙 Back",
		"ui.previous": "◀ Prev",
		"ui.next":     "Next ▶",
		"ui.retry":    "↻ Retry",

		"common.no_description":  "No description",
		"common.no_change":       "No change was needed.",
		"common.input_cancelled": "Input cancelled.",
		"common.reset_cancelled": "Reset cancelled.",

		"help.title":                     "GoUltroid Help",
		"help.summary":                   "%d commands across %d modules.",
		"help.command_title":             "Command: %s",
		"help.module_title":              "Module: %s",
		"help.commands_available":        "%d commands available in this module:",
		"help.field.category":            "Category",
		"help.field.permission":          "Permission",
		"help.field.invocation":          "Invocation",
		"help.field.usage":               "Usage",
		"help.field.aliases":             "Aliases",
		"help.field.group_authorization": "Group Authorization",
		"help.field.cooldown":            "Cooldown",
		"help.field.timeout":             "Timeout",
		"help.field.constraints":         "Constraints",
		"help.scope.groups_only":         "Groups only",
		"help.scope.pm_only":             "PM only",
		"help.scope.requires_reply":      "Requires reply",
		"help.run_with":                  "<i>Run with <code>%s</code></i>",
		"help.tip_details":               "<i>Tip: Use <code>%shelp &lt;command&gt;</code> for details.</i>",
		"help.tip_overview":              "💡 <i>Use <code>%shelp &lt;module&gt;</code> or <code>%shelp &lt;command&gt;</code> for details.</i>",
		"help.not_found":                 "Command or module %q not found.",
		"help.interactive_uncertain":     "Interactive help delivery could not be confirmed. Please retry the command.",

		"settings.dashboard.title":            "GoUltroid Settings Dashboard",
		"settings.dashboard.welcome":          "Welcome to the interactive configuration dashboard.\nSelect a category below to view and modify settings:\n",
		"settings.dashboard.categories":       "Available settings categories:",
		"settings.dashboard.inline_disabled":  "Inline buttons are disabled. Pass a category name to the settings command to browse its values.",
		"settings.category.title":             "Settings: %s",
		"settings.category.none":              "No settings configured for this category.",
		"settings.category.scope":             "Category: <b>%s</b> | Scope: <b>%s</b>",
		"settings.category.page":              "Page <b>%d / %d</b>. Pass a page number as the second argument to browse more settings.",
		"settings.category.use_config":        "Inline buttons are disabled. Use the config command to change values.",
		"settings.detail.type":                "Type",
		"settings.detail.current":             "Current Value",
		"settings.detail.origin":              "Origin",
		"settings.detail.default":             "Default",
		"settings.detail.scope":               "Scope",
		"settings.button.edit":                "⚙️ Edit %s",
		"settings.button.reset_default":       "🔄 Reset to Default",
		"settings.button.reset_override":      "↩ Reset Override",
		"settings.button.back_category":       "🔙 Back to %s",
		"settings.interaction.expired":        "Settings interaction expired. Reopen .settings.",
		"settings.interaction.invalid":        "Settings interaction is invalid. Reopen .settings.",
		"settings.interaction.closed":         "✅ Settings dashboard closed.",
		"settings.origin.chat_override":       "💬 Chat Override",
		"settings.origin.user_override":       "👤 User Override",
		"settings.origin.inherited_global":    "🌐 Inherited from Global",
		"settings.origin.global":              "🌐 Global Setting",
		"settings.origin.default":             "⚙️ Schema Default",
		"settings.category.general":           "⚙️ General",
		"settings.category.security":          "🛡 Security",
		"settings.category.moderation":        "👮 Moderation",
		"settings.category.automation":        "⚡ Automation",
		"settings.category.ui":                "🎨 UI Layout",
		"settings.category.advanced":          "🔧 Advanced",
		"settings.scope.global_to_chat":       "Scope: 🌐 Global [Click to Chat]",
		"settings.scope.chat_to_user":         "Scope: 💬 Chat [Click to User]",
		"settings.scope.user_to_global":       "Scope: 👤 User [Click to Global]",
		"settings.locale.title":               "Interface Language",
		"settings.locale.description":         "Language used by userbot and Assistant interfaces",
		"settings.notice.user_saved":          "User override saved.",
		"settings.notice.user_reset":          "User override reset.",
		"settings.notice.language_update_fail":"Language update failed. Retry safely.",
		"settings.reset.title":               "Reset this user override?",
		"settings.reset.body":                "This removes the user override and restores the inherited/default value. This action does not run until you confirm.",
		"settings.reset.confirm":             "✅ Confirm reset",
		"settings.reset.cancel":              "↩ Cancel",
		"assistant.home.greeting":            "Hey @%s. Please browse through the options",

		"downloader.title":                 "GoUltroid Media Downloader",
		"downloader.inline.title":          "Interactive downloader",
		"downloader.inline.description":    "Type: dl <https://media-url>",
		"downloader.inline.help":           "<b>Interactive downloader</b>\nType <code>dl &lt;https://media-url&gt;</code> in inline mode.",
		"downloader.result.title":           "Download media",
		"downloader.provider.extractor":     "Choose audio/video and a bounded output format",
		"downloader.provider.http":          "Download this direct HTTP(S) file",
		"downloader.button.audio":           "Audio",
		"downloader.button.video":           "Video",
		"downloader.button.download_file":   "Download File",
		"downloader.button.best":            "⭐ Best (native)",
		"downloader.choose_audio":           "Choose audio format",
		"downloader.choose_video":           "Choose video quality",
		"downloader.field.title":            "Title",
		"downloader.field.channel":          "Channel",
		"downloader.field.duration":         "Duration",
		"downloader.available_qualities":    "Available MP4 qualities:",
		"downloader.running":                "⬇️ <b>Downloading...</b>",
		"downloader.field.format":           "Format",
		"downloader.failed":                 "❌ <b>Download failed.</b>",
		"downloader.field.selection":        "Selection",
		"downloader.retry_hint":             "Retry the same selection or close and reopen the downloader.",
		"downloader.error":                  "❌ <b>Error downloading media.</b>\nReopen the downloader and try again.",
		"downloader.cancelled":              "✖ <b>Download cancelled.</b>",
		"downloader.session_invalid":        "Downloader session is invalid. Reopen it.",
		"downloader.audio_unsupported":       "This source does not support audio selection.",
		"downloader.video_unsupported":       "This source does not support video selection.",
		"downloader.no_previous":             "There is no previous downloader step.",
		"downloader.cancel_unconfirmed":      "Cancellation could not be confirmed. Please try again.",
		"downloader.delivery_failed":         "⚠️ <b>Download retained, but Telegram delivery failed.</b>\nReopen the downloader to retry. The retained asset remains safely stored.",
		"downloader.delivered":               "✅ <b>Download delivered to Telegram.</b>",
	})

	s.AddTranslations(LocaleIndonesian, map[string]string{
		"ui.close":    "❌ Tutup",
		"ui.home":     "🏠 Beranda",
		"ui.back":     "🔙 Kembali",
		"ui.previous": "◀ Sebelumnya",
		"ui.next":     "Berikutnya ▶",
		"ui.retry":    "↻ Coba lagi",

		"common.no_description":  "Tidak ada deskripsi",
		"common.no_change":       "Tidak ada perubahan yang diperlukan.",
		"common.input_cancelled": "Input dibatalkan.",
		"common.reset_cancelled": "Reset dibatalkan.",

		"help.title":                     "Bantuan GoUltroid",
		"help.summary":                   "%d perintah dalam %d modul.",
		"help.command_title":             "Perintah: %s",
		"help.module_title":              "Modul: %s",
		"help.commands_available":        "%d perintah tersedia di modul ini:",
		"help.field.category":            "Kategori",
		"help.field.permission":          "Izin",
		"help.field.invocation":          "Pemanggilan",
		"help.field.usage":               "Penggunaan",
		"help.field.aliases":             "Alias",
		"help.field.group_authorization": "Otorisasi Grup",
		"help.field.cooldown":            "Cooldown",
		"help.field.timeout":             "Batas Waktu",
		"help.field.constraints":         "Batasan",
		"help.scope.groups_only":         "Hanya grup",
		"help.scope.pm_only":             "Hanya PM",
		"help.scope.requires_reply":      "Harus membalas pesan",
		"help.run_with":                  "<i>Jalankan dengan <code>%s</code></i>",
		"help.tip_details":               "<i>Tip: Gunakan <code>%shelp &lt;command&gt;</code> untuk detail.</i>",
		"help.tip_overview":              "💡 <i>Gunakan <code>%shelp &lt;module&gt;</code> atau <code>%shelp &lt;command&gt;</code> untuk detail.</i>",
		"help.not_found":                 "Perintah atau modul %q tidak ditemukan.",
		"help.interactive_uncertain":     "Pengiriman bantuan interaktif tidak dapat dikonfirmasi. Silakan jalankan ulang perintah.",

		"settings.dashboard.title":            "Dashboard Pengaturan GoUltroid",
		"settings.dashboard.welcome":          "Selamat datang di dashboard konfigurasi interaktif.\nPilih kategori di bawah untuk melihat dan mengubah pengaturan:\n",
		"settings.dashboard.categories":       "Kategori pengaturan yang tersedia:",
		"settings.dashboard.inline_disabled":  "Tombol inline dinonaktifkan. Berikan nama kategori pada perintah settings untuk melihat nilainya.",
		"settings.category.title":             "Pengaturan: %s",
		"settings.category.none":              "Tidak ada pengaturan untuk kategori ini.",
		"settings.category.scope":             "Kategori: <b>%s</b> | Cakupan: <b>%s</b>",
		"settings.category.page":              "Halaman <b>%d / %d</b>. Berikan nomor halaman sebagai argumen kedua untuk melihat pengaturan lainnya.",
		"settings.category.use_config":        "Tombol inline dinonaktifkan. Gunakan perintah config untuk mengubah nilai.",
		"settings.detail.type":                "Tipe",
		"settings.detail.current":             "Nilai Saat Ini",
		"settings.detail.origin":              "Asal",
		"settings.detail.default":             "Default",
		"settings.detail.scope":               "Cakupan",
		"settings.button.edit":                "⚙️ Ubah %s",
		"settings.button.reset_default":       "🔄 Reset ke Default",
		"settings.button.reset_override":      "↩ Reset Override",
		"settings.button.back_category":       "🔙 Kembali ke %s",
		"settings.interaction.expired":        "Interaksi pengaturan kedaluwarsa. Buka kembali .settings.",
		"settings.interaction.invalid":        "Interaksi pengaturan tidak valid. Buka kembali .settings.",
		"settings.interaction.closed":         "✅ Dashboard pengaturan ditutup.",
		"settings.origin.chat_override":       "💬 Override Chat",
		"settings.origin.user_override":       "👤 Override Pengguna",
		"settings.origin.inherited_global":    "🌐 Diwarisi dari Global",
		"settings.origin.global":              "🌐 Pengaturan Global",
		"settings.origin.default":             "⚙️ Default Skema",
		"settings.category.general":           "⚙️ Umum",
		"settings.category.security":          "🛡 Keamanan",
		"settings.category.moderation":        "👮 Moderasi",
		"settings.category.automation":        "⚡ Otomasi",
		"settings.category.ui":                "🎨 Tampilan UI",
		"settings.category.advanced":          "🔧 Lanjutan",
		"settings.scope.global_to_chat":       "Cakupan: 🌐 Global [Klik ke Chat]",
		"settings.scope.chat_to_user":         "Cakupan: 💬 Chat [Klik ke Pengguna]",
		"settings.scope.user_to_global":       "Cakupan: 👤 Pengguna [Klik ke Global]",
		"settings.locale.title":               "Bahasa Antarmuka",
		"settings.locale.description":         "Bahasa yang digunakan antarmuka userbot dan Assistant",
		"settings.notice.user_saved":          "Override pengguna tersimpan.",
		"settings.notice.user_reset":          "Override pengguna direset.",
		"settings.notice.language_update_fail":"Pembaruan bahasa gagal. Silakan coba lagi.",
		"settings.reset.title":               "Reset override pengguna ini?",
		"settings.reset.body":                "Ini menghapus override pengguna dan mengembalikan nilai warisan/default. Tindakan baru dijalankan setelah Anda mengonfirmasi.",
		"settings.reset.confirm":             "✅ Konfirmasi reset",
		"settings.reset.cancel":              "↩ Batal",
		"assistant.home.greeting":            "Halo @%s. Silakan telusuri opsi",

		"downloader.title":                 "Pengunduh Media GoUltroid",
		"downloader.inline.title":          "Pengunduh interaktif",
		"downloader.inline.description":    "Ketik: dl <https://media-url>",
		"downloader.inline.help":           "<b>Pengunduh interaktif</b>\nKetik <code>dl &lt;https://media-url&gt;</code> pada mode inline.",
		"downloader.result.title":           "Unduh media",
		"downloader.provider.extractor":     "Pilih audio/video dan format keluaran terbatas",
		"downloader.provider.http":          "Unduh file HTTP(S) langsung ini",
		"downloader.button.audio":           "Audio",
		"downloader.button.video":           "Video",
		"downloader.button.download_file":   "Unduh File",
		"downloader.button.best":            "⭐ Terbaik (asli)",
		"downloader.choose_audio":           "Pilih format audio",
		"downloader.choose_video":           "Pilih kualitas video",
		"downloader.field.title":            "Judul",
		"downloader.field.channel":          "Kanal",
		"downloader.field.duration":         "Durasi",
		"downloader.available_qualities":    "Kualitas MP4 yang tersedia:",
		"downloader.running":                "⬇️ <b>Mengunduh...</b>",
		"downloader.field.format":           "Format",
		"downloader.failed":                 "❌ <b>Unduhan gagal.</b>",
		"downloader.field.selection":        "Pilihan",
		"downloader.retry_hint":             "Coba lagi pilihan yang sama atau tutup lalu buka kembali pengunduh.",
		"downloader.error":                  "❌ <b>Terjadi kesalahan saat mengunduh media.</b>\nBuka kembali pengunduh dan coba lagi.",
		"downloader.cancelled":              "✖ <b>Unduhan dibatalkan.</b>",
		"downloader.session_invalid":        "Sesi pengunduh tidak valid. Buka kembali.",
		"downloader.audio_unsupported":       "Sumber ini tidak mendukung pemilihan audio.",
		"downloader.video_unsupported":       "Sumber ini tidak mendukung pemilihan video.",
		"downloader.no_previous":             "Tidak ada langkah pengunduh sebelumnya.",
		"downloader.cancel_unconfirmed":      "Pembatalan tidak dapat dikonfirmasi. Silakan coba lagi.",
		"downloader.delivery_failed":         "⚠️ <b>Unduhan tersimpan, tetapi pengiriman ke Telegram gagal.</b>\nBuka kembali pengunduh untuk mencoba lagi. Aset tetap tersimpan dengan aman.",
		"downloader.delivered":               "✅ <b>Unduhan berhasil dikirim ke Telegram.</b>",
	})
}
