package localization

func (s *Service) loadUserbotUXTranslations() {
	s.AddTranslations(LocaleEnglish, map[string]string{
		"settings.cli.usage": "⚙️ <b>GoUltroid CLI Configuration Subsystem</b>\n\n<b>Usage:</b>\n• <code>.config get &lt;namespace:key&gt;</code>\n• <code>.config set &lt;namespace:key&gt; &lt;value&gt;</code>\n• <code>.config reset &lt;namespace:key&gt;</code>\n• <code>.config list [category]</code>\n• <code>.config history &lt;namespace:key&gt;</code>\n• <code>.config export</code>\n",
		"settings.cli.usage_get": "Usage: <code>.config get &lt;namespace:key&gt;</code>",
		"settings.cli.usage_set": "Usage: <code>.config set &lt;namespace:key&gt; &lt;value&gt;</code>",
		"settings.cli.usage_reset": "Usage: <code>.config reset &lt;namespace:key&gt;</code>",
		"settings.cli.usage_history": "Usage: <code>.config history &lt;namespace:key&gt;</code>",
		"settings.cli.value": "⚙️ <b>%s:%s</b> = <code>%s</code>",
		"settings.cli.set_failed": "Failed to set <b>%s:%s</b>: %s",
		"settings.cli.updated": "Setting updated:\n<code>%s:%s</code> = <code>%s</code>",
		"settings.cli.reset_failed": "Failed to reset <b>%s:%s</b>: %s",
		"settings.cli.reset_done": "Setting <code>%s:%s</code> reset to default.",
		"settings.cli.none": "No settings found.",
		"settings.cli.schema_title": "📋 <b>GoUltroid Configuration Schema</b>",
		"settings.cli.schema_item": "• <code>%s:%s</code> = <code>%s</code> (default: <code>%s</code>) [%s]\n  <i>%s</i>\n",
		"settings.cli.history_failed": "Error retrieving history: %s",
		"settings.cli.history_none": "No change history found for <code>%s:%s</code>.",
		"settings.cli.history_title": "📜 <b>Change History for</b> <code>%s:%s</code>",
		"settings.cli.history_item": "• <code>%s</code> ➔ <code>%s</code> by user <code>%d</code> at <code>%s</code>\n",
		"settings.cli.export_failed": "Export failed: %s",
		"settings.cli.export_result": "📤 <b>Global Settings Export:</b>\n<pre><code class=\"language-json\">%s</code></pre>",
		"settings.cli.unknown_action": "Unknown action <code>%s</code>. Use <code>.config</code> to see available commands.",
		"admin.action.ban": "ban",
		"admin.action.unban": "unban",
		"admin.action.kick": "kick",
		"admin.action.mute": "mute",
		"admin.action.unmute": "unmute",
		"admin.action.purge": "purge messages",
		"admin.action.promote": "promote",
		"admin.action.demote": "demote",
		"admin.action.warn": "warn",
		"admin.action.warns": "get warnings",
		"admin.action.resetwarns": "reset warnings",
		"admin.group_only": "%s can only be used in groups or supergroups.",
		"admin.owner_protected": "Cannot %s the owner.",
		"admin.moderation_unavailable": "Moderation service is not configured.",
		"admin.error.target_protected": "❌ Failed to %s: target is protected by Telegram admin hierarchy.",
		"admin.error.permission": "❌ Failed to %s: you or the Assistant bot do not have the required Telegram rights.",
		"admin.error.unsupported": "⚠️ This operation is not supported for this group type.",
		"admin.error.admin_limit": "❌ Failed: this group has reached the maximum number of administrators.",
		"admin.error.rights": "❌ Failed to %s: required Telegram admin rights are unavailable.",
		"admin.error.generic": "❌ Admin operation failed. Please try again.",
		"admin.reason_suffix": "\n<b>Reason:</b> %s",
		"admin.duration_suffix": " for <code>%s</code>",
		"admin.topic_suffix": " in topic <code>%d</code>",
		"admin.title_suffix": " with title <i>%s</i>",
		"admin.ban.success": "Banned user %s.%s",
		"admin.unban.success": "Unbanned user %s.",
		"admin.kick.success": "Kicked user %s.",
		"admin.mute.success": "Muted user %s%s.",
		"admin.unmute.success": "Unmuted user %s.",
		"admin.purge.reply_required": "Reply to the first message you want to purge.",
		"admin.purge.success": "🗑️ <b>Purged %d messages successfully%s!</b>",
		"admin.promote.success": "Promoted user %s%s to admin.",
		"admin.demote.success": "Demoted admin %s to a normal user.",
		"admin.no_reason": "No reason provided",
		"admin.warns_zero": "User <b>%s</b> has 0 active warnings.",
		"admin.recent_warnings": "\n\n<b>Recent warnings:</b>\n",
		"admin.warning_item": "%d. <i>%s</i> (by <code>%d</code>)\n",
		"media.info.none": "<b>No media found!</b> Please reply to a photo, video, audio, voice, sticker, or document.",
		"media.info.title": "📊 <b>Media Information</b>\n\n",
		"media.info.type": "• <b>Type</b>: <code>%s</code>\n",
		"media.info.filename": "• <b>File Name</b>: <code>%s</code>\n",
		"media.info.mime": "• <b>MIME Type</b>: <code>%s</code>\n",
		"media.info.size": "• <b>File Size</b>: <code>%s</code> (%d bytes)\n",
		"media.info.resolution": "• <b>Resolution</b>: <code>%dx%d</code>\n",
		"media.info.duration": "• <b>Duration</b>: <code>%s</code>\n",
		"media.extract.none": "<b>No media found!</b> Reply to a video, audio, or document to extract audio.",
		"media.extract.unsupported": "Cannot extract audio from a photo or sticker.",
		"media.extract.too_large": "<b>Media too large!</b> File size (%s) exceeds extraction limit (150MB).",
		"media.extract.progress": "<i>Downloading and extracting audio...</i>",
		"media.temp_failed": "Failed to create temporary directory.",
		"media.download_failed": "Failed to download media.",
		"media.extract.failed": "Audio extraction failed.",
		"media.extract.caption": "🎵 Extracted from: <code>%s</code>",
		"media.extract.send_failed": "Failed to send audio.",
		"media.convert.none": "<b>No media found!</b> Reply to a video or audio file to convert.",
		"media.convert.unsupported_format": "Unsupported target format <code>%s</code>. Supported: <code>mp4, mkv, mov, webm, avi, mp3, m4a, aac, ogg, opus, flac, wav</code>.",
		"media.convert.progress": "<i>Converting media to %s...</i>",
		"media.convert.failed": "Conversion failed.",
		"media.convert.caption": "🎬 Converted to: <code>%s</code>",
		"media.convert.send_failed": "Failed to send converted media.",
		"media.gif.none": "<b>No media found!</b> Reply to a video to convert to GIF.",
		"media.gif.progress": "<i>Converting video to GIF...</i>",
		"media.gif.failed": "GIF conversion failed.",
		"media.gif.caption": "🎞️ Converted to GIF",
		"media.gif.send_failed": "Failed to send GIF.",
		"media.sticker.none": "<b>No media found!</b> Reply to a video or animation to make a video sticker.",
		"media.sticker.progress": "<i>Generating video sticker (WebM 512x512)...</i>",
		"media.sticker.failed": "Video sticker generation failed.",
		"media.sticker.send_failed": "Failed to send video sticker.",
	})

	s.AddTranslations(LocaleIndonesian, map[string]string{
		"settings.cli.usage": "⚙️ <b>Subsistem Konfigurasi CLI GoUltroid</b>\n\n<b>Penggunaan:</b>\n• <code>.config get &lt;namespace:key&gt;</code>\n• <code>.config set &lt;namespace:key&gt; &lt;value&gt;</code>\n• <code>.config reset &lt;namespace:key&gt;</code>\n• <code>.config list [category]</code>\n• <code>.config history &lt;namespace:key&gt;</code>\n• <code>.config export</code>\n",
		"settings.cli.usage_get": "Penggunaan: <code>.config get &lt;namespace:key&gt;</code>",
		"settings.cli.usage_set": "Penggunaan: <code>.config set &lt;namespace:key&gt; &lt;value&gt;</code>",
		"settings.cli.usage_reset": "Penggunaan: <code>.config reset &lt;namespace:key&gt;</code>",
		"settings.cli.usage_history": "Penggunaan: <code>.config history &lt;namespace:key&gt;</code>",
		"settings.cli.value": "⚙️ <b>%s:%s</b> = <code>%s</code>",
		"settings.cli.set_failed": "Gagal mengatur <b>%s:%s</b>: %s",
		"settings.cli.updated": "Pengaturan diperbarui:\n<code>%s:%s</code> = <code>%s</code>",
		"settings.cli.reset_failed": "Gagal mereset <b>%s:%s</b>: %s",
		"settings.cli.reset_done": "Pengaturan <code>%s:%s</code> dikembalikan ke nilai default.",
		"settings.cli.none": "Tidak ada pengaturan yang ditemukan.",
		"settings.cli.schema_title": "📋 <b>Skema Konfigurasi GoUltroid</b>",
		"settings.cli.schema_item": "• <code>%s:%s</code> = <code>%s</code> (default: <code>%s</code>) [%s]\n  <i>%s</i>\n",
		"settings.cli.history_failed": "Gagal mengambil riwayat: %s",
		"settings.cli.history_none": "Tidak ada riwayat perubahan untuk <code>%s:%s</code>.",
		"settings.cli.history_title": "📜 <b>Riwayat Perubahan untuk</b> <code>%s:%s</code>",
		"settings.cli.history_item": "• <code>%s</code> ➔ <code>%s</code> oleh pengguna <code>%d</code> pada <code>%s</code>\n",
		"settings.cli.export_failed": "Ekspor gagal: %s",
		"settings.cli.export_result": "📤 <b>Ekspor Pengaturan Global:</b>\n<pre><code class=\"language-json\">%s</code></pre>",
		"settings.cli.unknown_action": "Aksi <code>%s</code> tidak dikenal. Gunakan <code>.config</code> untuk melihat perintah yang tersedia.",
		"admin.action.ban": "memblokir",
		"admin.action.unban": "membuka blokir",
		"admin.action.kick": "mengeluarkan",
		"admin.action.mute": "membisukan",
		"admin.action.unmute": "mengaktifkan suara",
		"admin.action.purge": "menghapus pesan",
		"admin.action.promote": "mempromosikan",
		"admin.action.demote": "menurunkan admin",
		"admin.action.warn": "memberi peringatan",
		"admin.action.warns": "mengambil peringatan",
		"admin.action.resetwarns": "mereset peringatan",
		"admin.group_only": "%s hanya dapat digunakan di grup atau supergroup.",
		"admin.owner_protected": "Tidak dapat %s owner.",
		"admin.moderation_unavailable": "Layanan moderasi belum dikonfigurasi.",
		"admin.error.target_protected": "❌ Gagal %s: target dilindungi oleh hierarki admin Telegram.",
		"admin.error.permission": "❌ Gagal %s: Anda atau bot Assistant tidak memiliki hak Telegram yang diperlukan.",
		"admin.error.unsupported": "⚠️ Operasi ini tidak didukung untuk tipe grup tersebut.",
		"admin.error.admin_limit": "❌ Gagal: batas maksimal admin di grup ini telah tercapai.",
		"admin.error.rights": "❌ Gagal %s: hak admin Telegram yang diperlukan tidak tersedia.",
		"admin.error.generic": "❌ Operasi admin gagal. Silakan coba lagi.",
		"admin.reason_suffix": "\n<b>Alasan:</b> %s",
		"admin.duration_suffix": " selama <code>%s</code>",
		"admin.topic_suffix": " di topik <code>%d</code>",
		"admin.title_suffix": " dengan gelar <i>%s</i>",
		"admin.ban.success": "Pengguna %s berhasil diblokir.%s",
		"admin.unban.success": "Blokir pengguna %s berhasil dibuka.",
		"admin.kick.success": "Pengguna %s berhasil dikeluarkan.",
		"admin.mute.success": "Pengguna %s berhasil dibisukan%s.",
		"admin.unmute.success": "Pengguna %s berhasil diaktifkan kembali suaranya.",
		"admin.purge.reply_required": "Balas pesan pertama yang ingin dihapus.",
		"admin.purge.success": "🗑️ <b>Berhasil menghapus %d pesan%s!</b>",
		"admin.promote.success": "Pengguna %s berhasil dipromosikan menjadi admin%s.",
		"admin.demote.success": "Admin %s berhasil diturunkan menjadi pengguna biasa.",
		"admin.no_reason": "Tidak ada alasan",
		"admin.warns_zero": "Pengguna <b>%s</b> memiliki 0 peringatan aktif.",
		"admin.recent_warnings": "\n\n<b>Peringatan terbaru:</b>\n",
		"admin.warning_item": "%d. <i>%s</i> (oleh <code>%d</code>)\n",
		"media.info.none": "<b>Media tidak ditemukan!</b> Balas foto, video, audio, voice, stiker, atau dokumen.",
		"media.info.title": "📊 <b>Informasi Media</b>\n\n",
		"media.info.type": "• <b>Tipe</b>: <code>%s</code>\n",
		"media.info.filename": "• <b>Nama File</b>: <code>%s</code>\n",
		"media.info.mime": "• <b>Tipe MIME</b>: <code>%s</code>\n",
		"media.info.size": "• <b>Ukuran File</b>: <code>%s</code> (%d byte)\n",
		"media.info.resolution": "• <b>Resolusi</b>: <code>%dx%d</code>\n",
		"media.info.duration": "• <b>Durasi</b>: <code>%s</code>\n",
		"media.extract.none": "<b>Media tidak ditemukan!</b> Balas video, audio, atau dokumen untuk mengekstrak audio.",
		"media.extract.unsupported": "Audio tidak dapat diekstrak dari foto atau stiker.",
		"media.extract.too_large": "<b>Media terlalu besar!</b> Ukuran file (%s) melebihi batas ekstraksi (150MB).",
		"media.extract.progress": "<i>Mengunduh dan mengekstrak audio...</i>",
		"media.temp_failed": "Gagal membuat direktori sementara.",
		"media.download_failed": "Gagal mengunduh media.",
		"media.extract.failed": "Ekstraksi audio gagal.",
		"media.extract.caption": "🎵 Diekstrak dari: <code>%s</code>",
		"media.extract.send_failed": "Gagal mengirim audio.",
		"media.convert.none": "<b>Media tidak ditemukan!</b> Balas file video atau audio untuk dikonversi.",
		"media.convert.unsupported_format": "Format target <code>%s</code> tidak didukung. Format yang didukung: <code>mp4, mkv, mov, webm, avi, mp3, m4a, aac, ogg, opus, flac, wav</code>.",
		"media.convert.progress": "<i>Mengonversi media ke %s...</i>",
		"media.convert.failed": "Konversi gagal.",
		"media.convert.caption": "🎬 Dikonversi ke: <code>%s</code>",
		"media.convert.send_failed": "Gagal mengirim media hasil konversi.",
		"media.gif.none": "<b>Media tidak ditemukan!</b> Balas video untuk dikonversi menjadi GIF.",
		"media.gif.progress": "<i>Mengonversi video menjadi GIF...</i>",
		"media.gif.failed": "Konversi GIF gagal.",
		"media.gif.caption": "🎞️ Dikonversi menjadi GIF",
		"media.gif.send_failed": "Gagal mengirim GIF.",
		"media.sticker.none": "<b>Media tidak ditemukan!</b> Balas video atau animasi untuk membuat stiker video.",
		"media.sticker.progress": "<i>Membuat stiker video (WebM 512x512)...</i>",
		"media.sticker.failed": "Pembuatan stiker video gagal.",
		"media.sticker.send_failed": "Gagal mengirim stiker video.",
	})
}
