// Code generated by featuregen. DO NOT EDIT.

package app

import (
	"github.com/inipew/goultroid/internal/module"
	"github.com/inipew/goultroid/plugins/clone"
)

var builtinModules = []module.Module{
	clone.Module,
}
