from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"missing anchor: {label}")
    return text.replace(old, new, 1)

# --- TaskManager: correlation-based cancellation ---
p = Path("internal/tasks/manager.go")
s = p.read_text()
anchor = '''// GetTask returns a copy of the active task if found.\nfunc (m *Manager) GetTask(taskID string) (Task, bool) {\n'''
insert = '''// CancelByCorrelationID cancels every active task sharing correlationID.\n// Execution producers use this to cancel logical work without owning physical\n// worker cancel functions or maintaining a parallel active-execution registry.\nfunc (m *Manager) CancelByCorrelationID(correlationID string) int {\n\tif correlationID == "" {\n\t\treturn 0\n\t}\n\tm.mu.RLock()\n\tvar cancels []context.CancelFunc\n\tfor _, tracked := range m.activeTasks {\n\t\tif tracked.task.CorrelationID == correlationID {\n\t\t\tcancels = append(cancels, tracked.cancel)\n\t\t}\n\t}\n\tm.mu.RUnlock()\n\tfor _, cancel := range cancels {\n\t\tcancel()\n\t}\n\treturn len(cancels)\n}\n\n// GetTask returns a copy of the active task if found.\nfunc (m *Manager) GetTask(taskID string) (Task, bool) {\n'''
s = replace_once(s, anchor, insert, "tasks correlation cancellation")
p.write_text(s)

# --- WorkerManager: own execution reservation lifecycle ---
p = Path("internal/workers/manager.go")
s = p.read_text()
old = '''// Submit dispatches a task to the designated worker pool with quota and lifecycle management.\nfunc (m *Manager) Submit(ctx context.Context, poolName string, task tasks.Task) error {\n'''
new = '''// Submit dispatches a task to the designated worker pool with quota and lifecycle management.\nfunc (m *Manager) Submit(ctx context.Context, poolName string, task tasks.Task) error {\n\treturn m.submit(ctx, poolName, task, nil)\n}\n\n// SubmitReserved submits work backed by a physical execution reservation.\n// WorkerManager owns the reservation after this call: it is released when the\n// task physically starts, or on any admission/cancellation failure before then.\nfunc (m *Manager) SubmitReserved(ctx context.Context, poolName string, task tasks.Task, reservation *ExecutionReservation) error {\n\tif reservation == nil {\n\t\treturn errors.New("execution reservation is nil")\n\t}\n\treturn m.submit(ctx, poolName, task, reservation)\n}\n\nfunc (m *Manager) submit(ctx context.Context, poolName string, task tasks.Task, reservation *ExecutionReservation) error {\n\treservationAccepted := false\n\tdefer func() {\n\t\tif reservation != nil && !reservationAccepted {\n\t\t\treservation.Release()\n\t\t}\n\t}()\n'''
s = replace_once(s, old, new, "worker submit wrapper")
old = '''\t\torigRun := task.Run\n\t\ttask.Run = func(runCtx context.Context) error {\n\t\t\tdefer cancel()\n'''
new = '''\t\torigRun := task.Run\n\t\ttask.Run = func(runCtx context.Context) error {\n\t\t\tif reservation != nil {\n\t\t\t\treservation.Release()\n\t\t\t}\n\t\t\tdefer cancel()\n'''
s = replace_once(s, old, new, "worker reservation release on physical start")
old = '''\t\tgo m.admitTask(admissionCtx, pool, tm, taskCtx, cancel, task)\n\t\treturn nil\n\t}\n\n\treturn pool.Submit(ctx, task)\n}\n\nfunc (m *Manager) admitTask(admissionCtx context.Context, pool *Pool, tm *tasks.Manager, taskCtx context.Context, cancel context.CancelFunc, task tasks.Task) {\n'''
new = '''\t\treservationAccepted = true\n\t\tgo m.admitTask(admissionCtx, pool, tm, taskCtx, cancel, task, reservation)\n\t\treturn nil\n\t}\n\n\tif reservation != nil {\n\t\treturn errors.New("execution reservation requires TaskManager lifecycle tracking")\n\t}\n\treturn pool.Submit(ctx, task)\n}\n\nfunc (m *Manager) admitTask(admissionCtx context.Context, pool *Pool, tm *tasks.Manager, taskCtx context.Context, cancel context.CancelFunc, task tasks.Task, reservation *ExecutionReservation) {\n'''
s = replace_once(s, old, new, "worker admit reservation handoff")
old = '''\tif err == nil {\n\t\treturn\n\t}\n\tcancel()\n'''
new = '''\tif err == nil {\n\t\treturn\n\t}\n\tif reservation != nil {\n\t\treservation.Release()\n\t}\n\tcancel()\n'''
s = replace_once(s, old, new, "worker release reservation on admission failure")
p.write_text(s)

# --- JobManager: own active attempt cancellation ---
p = Path("internal/jobs/manager.go")
s = p.read_text()
s = replace_once(s,
'''\tcompletionSeq     uint64\n\tcompletionWaiters map[string]map[uint64]chan error\n''',
'''\tcompletionSeq     uint64\n\tcompletionWaiters map[string]map[uint64]chan error\n\tactiveAttempts    map[string]map[string]context.CancelFunc\n''', "job active attempts field")
s = replace_once(s,
'''\t\tcompletionWaiters: make(map[string]map[uint64]chan error),\n\t\tretention:         7 * 24 * time.Hour,\n''',
'''\t\tcompletionWaiters: make(map[string]map[uint64]chan error),\n\t\tactiveAttempts:    make(map[string]map[string]context.CancelFunc),\n\t\tretention:         7 * 24 * time.Hour,\n''', "job active attempts init")
s = replace_once(s,
'''func (m *Manager) Trigger(ctx context.Context, jobID string) error {\n\tm.mu.Lock()\n''',
'''func (m *Manager) Trigger(ctx context.Context, jobID string) error {\n\tif ctx == nil {\n\t\tctx = context.Background()\n\t}\n\tm.mu.Lock()\n''', "job trigger nil context")
old = '''\ttask := tasks.Task{\n\t\tID:             fmt.Sprintf("task:%s:%d", jobID, time.Now().UnixNano()),\n\t\tOwner:          owner,\n'''
new = '''\ttaskID := fmt.Sprintf("task:%s:%d", jobID, time.Now().UnixNano())\n\tattemptCtx, attemptCancel := context.WithCancel(ctx)\n\tm.registerActiveAttempt(jobID, taskID, attemptCancel)\n\tstopAttemptWatch := context.AfterFunc(attemptCtx, func() {\n\t\tm.unregisterActiveAttempt(jobID, taskID)\n\t})\n\n\ttask := tasks.Task{\n\t\tID:             taskID,\n\t\tOwner:          owner,\n'''
s = replace_once(s, old, new, "job task attempt context")
old = '''\t\tRun: func(taskCtx context.Context) error {\n\t\t\tif idemp != nil && idempotencyKey != "" {\n'''
new = '''\t\tRun: func(taskCtx context.Context) error {\n\t\t\tdefer func() {\n\t\t\t\tstopAttemptWatch()\n\t\t\t\tm.unregisterActiveAttempt(jobID, taskID)\n\t\t\t\tattemptCancel()\n\t\t\t}()\n\t\t\tif idemp != nil && idempotencyKey != "" {\n'''
s = replace_once(s, old, new, "job attempt cleanup")
old = '''\t\t\tm.mu.Lock()\n\t\t\tif err != nil {\n\t\t\t\tjob.State = StateFailed\n\t\t\t\tjob.LastError = err.Error()\n\t\t\t} else {\n\t\t\t\tjob.State = StateCompleted\n\t\t\t\tjob.LastError = ""\n\t\t\t}\n'''
new = '''\t\t\tm.mu.Lock()\n\t\t\tif job.State == StateCancelled {\n\t\t\t\tjob.LastError = context.Canceled.Error()\n\t\t\t} else if err != nil {\n\t\t\t\tjob.State = StateFailed\n\t\t\t\tjob.LastError = err.Error()\n\t\t\t} else {\n\t\t\t\tjob.State = StateCompleted\n\t\t\t\tjob.LastError = ""\n\t\t\t}\n'''
s = replace_once(s, old, new, "job preserve cancelled terminal state")
old = '''\tif err := m.submitter.Submit(ctx, pool, task); err != nil {\n\t\tm.rollbackTrigger(ctx, job, previousState, previousLastRun, err.Error())\n\t\treturn fmt.Errorf("submit job %q to pool %q: %w", jobID, pool, err)\n\t}\n'''
new = '''\tif err := m.submitter.Submit(attemptCtx, pool, task); err != nil {\n\t\tstopAttemptWatch()\n\t\tm.unregisterActiveAttempt(jobID, taskID)\n\t\tattemptCancel()\n\t\tm.rollbackTrigger(ctx, job, previousState, previousLastRun, err.Error())\n\t\treturn fmt.Errorf("submit job %q to pool %q: %w", jobID, pool, err)\n\t}\n'''
s = replace_once(s, old, new, "job submit attempt context")
anchor = '''func (m *Manager) registerCompletionWaiter(jobID string) (uint64, <-chan error) {\n'''
insert = '''func (m *Manager) registerActiveAttempt(jobID, taskID string, cancel context.CancelFunc) {\n\tm.mu.Lock()\n\tdefer m.mu.Unlock()\n\tattempts := m.activeAttempts[jobID]\n\tif attempts == nil {\n\t\tattempts = make(map[string]context.CancelFunc)\n\t\tm.activeAttempts[jobID] = attempts\n\t}\n\tattempts[taskID] = cancel\n}\n\nfunc (m *Manager) unregisterActiveAttempt(jobID, taskID string) {\n\tm.mu.Lock()\n\tdefer m.mu.Unlock()\n\tattempts := m.activeAttempts[jobID]\n\tif attempts == nil {\n\t\treturn\n\t}\n\tdelete(attempts, taskID)\n\tif len(attempts) == 0 {\n\t\tdelete(m.activeAttempts, jobID)\n\t}\n}\n\nfunc (m *Manager) detachActiveAttemptsLocked(jobID string) []context.CancelFunc {\n\tattempts := m.activeAttempts[jobID]\n\tif len(attempts) == 0 {\n\t\tdelete(m.activeAttempts, jobID)\n\t\treturn nil\n\t}\n\tcancels := make([]context.CancelFunc, 0, len(attempts))\n\tfor _, cancel := range attempts {\n\t\tcancels = append(cancels, cancel)\n\t}\n\tdelete(m.activeAttempts, jobID)\n\treturn cancels\n}\n\nfunc cancelAttempts(cancels []context.CancelFunc) {\n\tfor _, cancel := range cancels {\n\t\tcancel()\n\t}\n}\n\nfunc (m *Manager) registerCompletionWaiter(jobID string) (uint64, <-chan error) {\n'''
s = replace_once(s, anchor, insert, "job attempt registry helpers")
old = '''// Cancel cancels and removes a specific job.\nfunc (m *Manager) Cancel(ctx context.Context, jobID string) error {\n\tm.mu.Lock()\n\tjob, exists := m.jobs[jobID]\n\tif !exists {\n\t\tm.mu.Unlock()\n\t\treturn fmt.Errorf("job %q not found", jobID)\n\t}\n\tjob.State = StateCancelled\n\tdelete(m.jobs, jobID)\n\trepo := m.repo\n\tm.mu.Unlock()\n\n\tif repo != nil {\n\t\tif err := repo.Delete(ctx, jobID); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n\treturn nil\n}\n\n// CancelByOwner cancels and removes all jobs belonging to a specific owner (e.g. on plugin disable).\nfunc (m *Manager) CancelByOwner(owner string) int {\n\tm.mu.Lock()\n\tcancelled := 0\n\tfor id, j := range m.jobs {\n\t\tif j.Owner == owner {\n\t\t\tj.State = StateCancelled\n\t\t\tdelete(m.jobs, id)\n\t\t\tcancelled++\n\t\t}\n\t}\n\trepo := m.repo\n\tm.mu.Unlock()\n\n\tif repo != nil {\n\t\t_, _ = repo.DeleteByOwner(context.Background(), owner)\n\t}\n\treturn cancelled\n}\n'''
new = '''// Cancel cancels the active Task attempt hierarchy before removing the durable job.\nfunc (m *Manager) Cancel(ctx context.Context, jobID string) error {\n\tif ctx == nil {\n\t\tctx = context.Background()\n\t}\n\tm.mu.Lock()\n\tjob, exists := m.jobs[jobID]\n\tif !exists {\n\t\tm.mu.Unlock()\n\t\treturn fmt.Errorf("job %q not found", jobID)\n\t}\n\tjob.State = StateCancelled\n\tjob.LastError = context.Canceled.Error()\n\tcancels := m.detachActiveAttemptsLocked(jobID)\n\tdelete(m.jobs, jobID)\n\trepo := m.repo\n\tm.mu.Unlock()\n\n\tcancelAttempts(cancels)\n\tm.notifyCompletion(jobID, context.Canceled)\n\tif repo != nil {\n\t\tif err := repo.Delete(ctx, jobID); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n\treturn nil\n}\n\n// CancelByOwner cancels active attempts and removes all jobs belonging to owner.\nfunc (m *Manager) CancelByOwner(owner string) int {\n\tm.mu.Lock()\n\tcancelled := 0\n\tvar cancels []context.CancelFunc\n\tvar jobIDs []string\n\tfor id, j := range m.jobs {\n\t\tif j.Owner == owner {\n\t\t\tj.State = StateCancelled\n\t\t\tj.LastError = context.Canceled.Error()\n\t\t\tcancels = append(cancels, m.detachActiveAttemptsLocked(id)...)\n\t\t\tjobIDs = append(jobIDs, id)\n\t\t\tdelete(m.jobs, id)\n\t\t\tcancelled++\n\t\t}\n\t}\n\trepo := m.repo\n\tm.mu.Unlock()\n\n\tcancelAttempts(cancels)\n\tfor _, jobID := range jobIDs {\n\t\tm.notifyCompletion(jobID, context.Canceled)\n\t}\n\tif repo != nil {\n\t\t_, _ = repo.DeleteByOwner(context.Background(), owner)\n\t}\n\treturn cancelled\n}\n'''
s = replace_once(s, old, new, "job hierarchical cancel")
p.write_text(s)

# --- Scheduler: remove parallel active-execution registry, use TaskManager correlation cancellation ---
p = Path("internal/scheduler/engine.go")
s = p.read_text()
s = replace_once(s,
'''\tactiveJobs   map[int64]map[string]context.CancelFunc\n\tactiveJobsMu sync.Mutex\n\n''', '', "scheduler active jobs fields")
s = replace_once(s,
'''\t\tactiveJobs:     make(map[int64]map[string]context.CancelFunc),\n''', '', "scheduler active jobs init")
old = '''\te.cancelActiveJob(jobID)\n\te.notifyWake()\n'''
new = '''\tif e.taskMgr != nil {\n\t\te.taskMgr.CancelByCorrelationID(scheduledTaskCorrelation(jobID))\n\t}\n\te.notifyWake()\n'''
s = replace_once(s, old, new, "scheduler cancel via task manager")
start = s.index('func (e *Engine) registerActiveJob(')
end = s.index('func (e *Engine) runLoop(', start)
s = s[:start] + '''func scheduledTaskCorrelation(jobID int64) string {\n\treturn fmt.Sprintf("scheduler:job:%d", jobID)\n}\n\n''' + s[end:]
old = '''\t\tif e.workers != nil {\n\t\t\treservation := reservations[i]\n\t\t\ttaskID := fmt.Sprintf("sched-%d-%s", j.ID, j.ClaimToken)\n\t\t\tjobCtx, cancel := context.WithCancel(e.ctx)\n\t\t\tstopReservationWatch := context.AfterFunc(jobCtx, reservation.Release)\n\t\t\te.registerActiveJob(j.ID, j.ClaimToken, cancel)\n\t\t\ttaskName := fmt.Sprintf("%s-%d", j.ActionType, j.ID)\n\n\t\t\ttask := tasks.Task{\n\t\t\t\tID:        taskID,\n\t\t\t\tOwner:     "scheduler",\n\t\t\t\tName:      taskName,\n\t\t\t\tTimeout:   90 * time.Second,\n\t\t\t\tCreatedAt: time.Now().UTC(),\n\t\t\t\tRun: func(taskCtx context.Context) error {\n\t\t\t\t\t// The physical worker has incremented Busy before Run, so the\n\t\t\t\t\t// reservation can now transition to the real busy accounting.\n\t\t\t\t\treservation.Release()\n\t\t\t\t\tstopReservationWatch()\n\t\t\t\t\tdefer func() {\n\t\t\t\t\t\te.unregisterActiveJob(j.ID, j.ClaimToken)\n\t\t\t\t\t\tcancel()\n\t\t\t\t\t\te.notifyWake()\n\t\t\t\t\t}()\n\t\t\t\t\te.executeJob(taskCtx, j, cancel)\n\t\t\t\t\treturn nil\n\t\t\t\t},\n\t\t\t}\n\n\t\t\tif err := e.workers.Submit(jobCtx, workers.PoolScheduler, task); err != nil {\n\t\t\t\tstopReservationWatch()\n\t\t\t\treservation.Release()\n\t\t\t\te.logger.Error("failed to submit scheduled job to worker pool", zap.Int64("job_id", j.ID), zap.Error(err))\n\t\t\t\te.unregisterActiveJob(j.ID, j.ClaimToken)\n\t\t\t\tcancel()\n\t\t\t}\n\t\t\tcontinue\n\t\t}\n\n\t\t// Compatibility path for tests/embedders without WorkerManager. It is\n\t\t// intentionally synchronous: Scheduler no longer owns physical concurrency.\n\t\tjobCtx, cancel := context.WithCancel(e.ctx)\n\t\te.registerActiveJob(j.ID, j.ClaimToken, cancel)\n\t\te.executeJob(jobCtx, j, cancel)\n\t\te.unregisterActiveJob(j.ID, j.ClaimToken)\n\t\tcancel()\n'''
new = '''\t\tif e.workers != nil {\n\t\t\treservation := reservations[i]\n\t\t\ttaskID := fmt.Sprintf("sched-%d-%s", j.ID, j.ClaimToken)\n\t\t\ttaskName := fmt.Sprintf("%s-%d", j.ActionType, j.ID)\n\n\t\t\ttask := tasks.Task{\n\t\t\t\tID:            taskID,\n\t\t\t\tOwner:         "scheduler",\n\t\t\t\tName:          taskName,\n\t\t\t\tCorrelationID: scheduledTaskCorrelation(j.ID),\n\t\t\t\tTimeout:       90 * time.Second,\n\t\t\t\tCreatedAt:     time.Now().UTC(),\n\t\t\t\tRun: func(taskCtx context.Context) error {\n\t\t\t\t\texecCtx, cancel := context.WithCancel(taskCtx)\n\t\t\t\t\tdefer cancel()\n\t\t\t\t\tdefer e.notifyWake()\n\t\t\t\t\te.executeJob(execCtx, j, cancel)\n\t\t\t\t\treturn nil\n\t\t\t\t},\n\t\t\t}\n\n\t\t\tif err := e.workers.SubmitReserved(e.ctx, workers.PoolScheduler, task, reservation); err != nil {\n\t\t\t\te.logger.Error("failed to submit scheduled job to worker pool", zap.Int64("job_id", j.ID), zap.Error(err))\n\t\t\t}\n\t\t\tcontinue\n\t\t}\n\n\t\t// Compatibility path for tests/embedders without WorkerManager. It is\n\t\t// intentionally synchronous: Scheduler no longer owns physical concurrency.\n\t\tjobCtx, cancel := context.WithCancel(e.ctx)\n\t\te.executeJob(jobCtx, j, cancel)\n\t\tcancel()\n'''
s = replace_once(s, old, new, "scheduler task-owned execution")
p.write_text(s)

# Replace scheduler cancellation tests with TaskManager-owned cancellation behavior.
p = Path("internal/scheduler/engine_cancellation_test.go")
p.write_text('''package scheduler\n\nimport (\n\t"context"\n\t"testing"\n\t"time"\n\n\t"github.com/inipew/goultroid/internal/database"\n\t"github.com/inipew/goultroid/internal/tasks"\n\t"go.uber.org/zap"\n)\n\nfunc TestEngineCancelDelegatesExecutionCancellationToTaskManager(t *testing.T) {\n\tdb, err := database.Open(":memory:")\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n\tdefer db.Close()\n\n\ttm := tasks.NewManager()\n\tengine := NewEngine(NewSQLiteRepository(db.DB), nil, nil, nil, zap.NewNop())\n\tengine.taskMgr = tm\n\n\tctx, _, err := tm.Register(context.Background(), tasks.Task{\n\t\tID:            "sched-42-a",\n\t\tOwner:         "scheduler",\n\t\tName:          "test",\n\t\tCorrelationID: scheduledTaskCorrelation(42),\n\t\tRun:           func(context.Context) error { return nil },\n\t})\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n\n\tif err := engine.Cancel(context.Background(), 42); err != nil {\n\t\tt.Fatal(err)\n\t}\n\tselect {\n\tcase <-ctx.Done():\n\tcase <-time.After(time.Second):\n\t\tt.Fatal("scheduler cancellation did not cancel correlated task")\n\t}\n}\n\nfunc TestScheduledTaskCorrelationIsPerJob(t *testing.T) {\n\tif scheduledTaskCorrelation(1) == scheduledTaskCorrelation(2) {\n\t\tt.Fatal("distinct scheduled jobs must not share correlation IDs")\n\t}\n}\n''')

# Add JobManager hierarchical cancellation coverage.
Path("internal/jobs/cancellation_test.go").write_text('''package jobs\n\nimport (\n\t"context"\n\t"errors"\n\t"sync"\n\t"testing"\n\t"time"\n\n\t"github.com/inipew/goultroid/internal/tasks"\n)\n\ntype blockingSubmitter struct {\n\tmu   sync.Mutex\n\ttask tasks.Task\n\tctx  context.Context\n}\n\nfunc (b *blockingSubmitter) Submit(ctx context.Context, _ string, task tasks.Task) error {\n\tb.mu.Lock()\n\tb.task = task\n\tb.ctx = ctx\n\tb.mu.Unlock()\n\treturn nil\n}\n\nfunc TestCancelPropagatesToActiveJobAttempt(t *testing.T) {\n\ts := &blockingSubmitter{}\n\tm := NewManager(s)\n\tif err := m.Register(Job{\n\t\tID: "cancel-me", Owner: "plugin:test",\n\t\tRun: func(ctx context.Context) error { <-ctx.Done(); return ctx.Err() },\n\t}); err != nil {\n\t\tt.Fatal(err)\n\t}\n\tif err := m.Trigger(context.Background(), "cancel-me"); err != nil {\n\t\tt.Fatal(err)\n\t}\n\ts.mu.Lock()\n\tattemptCtx := s.ctx\n\ts.mu.Unlock()\n\tif attemptCtx == nil {\n\t\tt.Fatal("submitter did not receive attempt context")\n\t}\n\tif err := m.Cancel(context.Background(), "cancel-me"); err != nil {\n\t\tt.Fatal(err)\n\t}\n\tselect {\n\tcase <-attemptCtx.Done():\n\t\tif !errors.Is(attemptCtx.Err(), context.Canceled) {\n\t\t\tt.Fatalf("attempt error = %v", attemptCtx.Err())\n\t\t}\n\tcase <-time.After(time.Second):\n\t\tt.Fatal("active attempt was not cancelled")\n\t}\n}\n\nfunc TestCancelByOwnerPropagatesToAllActiveAttempts(t *testing.T) {\n\ttype submitted struct { ctx context.Context; task tasks.Task }\n\tvar mu sync.Mutex\n\tvar all []submitted\n\ts := taskSubmitterFunc(func(ctx context.Context, _ string, task tasks.Task) error {\n\t\tmu.Lock(); all = append(all, submitted{ctx: ctx, task: task}); mu.Unlock(); return nil\n\t})\n\tm := NewManager(s)\n\tfor _, id := range []string{"a", "b"} {\n\t\tif err := m.Register(Job{ID: id, Owner: "plugin:x", Run: func(context.Context) error { return nil }}); err != nil { t.Fatal(err) }\n\t\tif err := m.Trigger(context.Background(), id); err != nil { t.Fatal(err) }\n\t}\n\tif got := m.CancelByOwner("plugin:x"); got != 2 { t.Fatalf("cancelled=%d want 2", got) }\n\tmu.Lock(); defer mu.Unlock()\n\tfor _, sub := range all {\n\t\tselect { case <-sub.ctx.Done(): default: t.Fatalf("task %s context not cancelled", sub.task.ID) }\n\t}\n}\n\ntype taskSubmitterFunc func(context.Context, string, tasks.Task) error\nfunc (f taskSubmitterFunc) Submit(ctx context.Context, pool string, task tasks.Task) error { return f(ctx, pool, task) }\n''')

# Add TaskManager correlation cancellation coverage.
Path("internal/tasks/correlation_test.go").write_text('''package tasks\n\nimport (\n\t"context"\n\t"testing"\n)\n\nfunc TestCancelByCorrelationID(t *testing.T) {\n\tm := NewManager()\n\tctxA, _, err := m.Register(context.Background(), Task{ID: "a", Owner: "x", CorrelationID: "job:1", Run: func(context.Context) error { return nil }})\n\tif err != nil { t.Fatal(err) }\n\tctxB, _, err := m.Register(context.Background(), Task{ID: "b", Owner: "x", CorrelationID: "job:2", Run: func(context.Context) error { return nil }})\n\tif err != nil { t.Fatal(err) }\n\tif got := m.CancelByCorrelationID("job:1"); got != 1 { t.Fatalf("cancelled=%d want 1", got) }\n\tselect { case <-ctxA.Done(): default: t.Fatal("correlated task was not cancelled") }\n\tselect { case <-ctxB.Done(): t.Fatal("unrelated task was cancelled"); default: }\n}\n''')
