// Command featuregen generates internal/app/generated_modules.go from plugin
// directories that expose a package-level Module value. Discovery is static:
// there is no reflection, dynamic loading, or init-based registration.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type entry struct {
	alias      string
	importPath string
}

func main() {
	root, err := repoRoot()
	if err != nil {
		panic(err)
	}
	entries, err := discover(filepath.Join(root, "plugins"), root)
	if err != nil {
		panic(err)
	}

	var b strings.Builder
	b.WriteString("// Code generated by featuregen. DO NOT EDIT.\n\npackage app\n\nimport (\n")
	b.WriteString("\t\"github.com/inipew/goultroid/internal/module\"\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\t%s %q\n", e.alias, e.importPath))
	}
	b.WriteString(")\n\nvar builtinModules = []module.Module{\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\t%s.Module,\n", e.alias))
	}
	b.WriteString("}\n")

	output := filepath.Join(root, "internal", "app", "generated_modules.go")
	if err := os.WriteFile(output, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not locate repository root from %s", wd)
		}
	}
}

func discover(root, repoRoot string) ([]entry, error) {
	var result []entry
	seenAliases := make(map[string]string)
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || info.Name() != "module.go" {
			return nil
		}
		f, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if err != nil {
			return err
		}
		found := false
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.VAR {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for _, name := range vs.Names {
					if name.Name == "Module" {
						found = true
					}
				}
			}
		}
		if !found {
			return nil
		}
		dir := filepath.ToSlash(filepath.Dir(path))
		rel, err := filepath.Rel(repoRoot, dir)
		if err != nil {
			return err
		}
		alias := filepath.Base(dir)
		if previous, exists := seenAliases[alias]; exists && previous != rel {
			return fmt.Errorf("duplicate generated import alias %q for %s and %s", alias, previous, rel)
		}
		seenAliases[alias] = rel
		result = append(result, entry{alias: alias, importPath: "github.com/inipew/goultroid/" + filepath.ToSlash(rel)})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(result, func(i, j int) bool { return result[i].importPath < result[j].importPath })
	return result, nil
}
