// Command featuregen generates internal/app/generated_modules.go from plugin
// directories that expose a package-level Module value. Discovery is static:
// there is no reflection, dynamic loading, or init-based registration.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var moduleIDRegex = regexp.MustCompile(`^[a-z0-9][a-z0-9_-]*$`)

type entry struct {
	alias      string
	importPath string
	id         string
}

func main() {
	root, err := repoRoot()
	if err != nil {
		panic(err)
	}
	entries, err := discover(filepath.Join(root, "plugins"), root)
	if err != nil {
		panic(err)
	}

	content := generate(entries)
	output := filepath.Join(root, "internal", "app", "generated_modules.go")
	if err := os.WriteFile(output, []byte(content), 0o644); err != nil {
		panic(err)
	}
}

func generate(entries []entry) string {
	var b strings.Builder
	b.WriteString("// Code generated by featuregen. DO NOT EDIT.\n\npackage app\n\nimport (\n")
	b.WriteString("\t\"github.com/inipew/goultroid/internal/module\"\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\t%s %q\n", e.alias, e.importPath))
	}
	b.WriteString(")\n\nvar builtinModules = []module.Module{\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\t%s.Module,\n", e.alias))
	}
	b.WriteString("}\n")
	return b.String()
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not locate repository root from %s", wd)
		}
	}
}

func discover(root, repoRoot string) ([]entry, error) {
	var result []entry
	seenAliases := make(map[string]string)
	seenIDs := make(map[string]string)

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || info.Name() != "module.go" {
			return nil
		}

		dir := filepath.Dir(path)
		fset := token.NewFileSet()
		pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
			return !strings.HasSuffix(fi.Name(), "_test.go")
		}, 0)
		if err != nil {
			return fmt.Errorf("failed to parse directory %s: %w", dir, err)
		}

		var modulePkg *ast.Package
		for _, pkg := range pkgs {
			if _, ok := pkg.Files[path]; ok {
				modulePkg = pkg
				break
			}
		}
		if modulePkg == nil {
			return fmt.Errorf("module.go not found in parsed package in %s", dir)
		}

		moduleTypeName := findModuleTypeNameInPkg(modulePkg)
		if moduleTypeName == "" {
			return fmt.Errorf("%s: module.go must declare package-level 'var Module'", path)
		}

		hasManifest, manifestID := checkManifestMethodInPkg(modulePkg, moduleTypeName)
		if !hasManifest {
			return fmt.Errorf("%s: type %s must implement Manifest() module.Manifest", path, moduleTypeName)
		}
		if manifestID == "" {
			return fmt.Errorf("%s: Manifest() must specify non-empty ID", path)
		}
		if !moduleIDRegex.MatchString(manifestID) {
			return fmt.Errorf("%s: invalid module ID %q (must match ^[a-z0-9][a-z0-9_-]*$)", path, manifestID)
		}

		if !checkRegisterMethodInPkg(modulePkg, moduleTypeName) {
			return fmt.Errorf("%s: type %s must implement Register(context.Context, *module.Runtime) error", path, moduleTypeName)
		}

		slashDir := filepath.ToSlash(dir)
		rel, err := filepath.Rel(repoRoot, slashDir)
		if err != nil {
			return err
		}
		alias := filepath.Base(slashDir)
		if previous, exists := seenAliases[alias]; exists && previous != rel {
			return fmt.Errorf("duplicate generated import alias %q for %s and %s", alias, previous, rel)
		}
		if previous, exists := seenIDs[manifestID]; exists && previous != rel {
			return fmt.Errorf("duplicate module ID %q in %s and %s", manifestID, previous, rel)
		}

		seenAliases[alias] = rel
		seenIDs[manifestID] = rel
		result = append(result, entry{
			alias:      alias,
			importPath: "github.com/inipew/goultroid/" + filepath.ToSlash(rel),
			id:         manifestID,
		})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(result, func(i, j int) bool { return result[i].importPath < result[j].importPath })
	return result, nil
}

func findModuleTypeNameInPkg(pkg *ast.Package) string {
	for _, f := range pkg.Files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.VAR {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for i, name := range vs.Names {
					if name.Name == "Module" {
						if vs.Type != nil {
							if ident, ok := vs.Type.(*ast.Ident); ok {
								return ident.Name
							}
						}
						if len(vs.Values) > i {
							switch v := vs.Values[i].(type) {
							case *ast.CompositeLit:
								if ident, ok := v.Type.(*ast.Ident); ok {
									return ident.Name
								}
							case *ast.CallExpr:
								if ident, ok := v.Fun.(*ast.Ident); ok {
									return ident.Name
								}
							}
						}
					}
				}
			}
		}
	}
	return ""
}

func checkManifestMethodInPkg(pkg *ast.Package, typeName string) (bool, string) {
	for _, f := range pkg.Files {
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || len(fn.Recv.List) == 0 {
				continue
			}
			if getReceiverTypeName(fn.Recv.List[0].Type) != typeName {
				continue
			}
			if fn.Name.Name == "Manifest" {
				id := extractManifestID(fn)
				return true, id
			}
		}
	}
	return false, ""
}

func checkRegisterMethodInPkg(pkg *ast.Package, typeName string) bool {
	for _, f := range pkg.Files {
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || len(fn.Recv.List) == 0 {
				continue
			}
			if getReceiverTypeName(fn.Recv.List[0].Type) != typeName {
				continue
			}
			if fn.Name.Name == "Register" {
				return true
			}
		}
	}
	return false
}

func getReceiverTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	}
	return ""
}

func extractManifestID(fn *ast.FuncDecl) string {
	if fn.Body == nil {
		return ""
	}
	for _, stmt := range fn.Body.List {
		ret, ok := stmt.(*ast.ReturnStmt)
		if !ok {
			continue
		}
		for _, res := range ret.Results {
			cl, ok := res.(*ast.CompositeLit)
			if !ok {
				continue
			}
			for _, elt := range cl.Elts {
				kve, ok := elt.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				if k, ok := kve.Key.(*ast.Ident); ok && k.Name == "ID" {
					if lit, ok := kve.Value.(*ast.BasicLit); ok && lit.Kind == token.STRING {
						return strings.Trim(lit.Value, `"`)
					}
				}
			}
		}
	}
	return ""
}
