// Command featuregen generates internal/app/generated_modules.go from plugin
// directories that expose a package-level Module value. Discovery is static:
// there is no reflection, dynamic loading, or init-based registration.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type entry struct {
	alias      string
	importPath string
}

func main() {
	entries, err := discover("plugins")
	if err != nil {
		panic(err)
	}

	var b strings.Builder
	b.WriteString("// Code generated by featuregen. DO NOT EDIT.\n\npackage app\n\nimport (\n")
	b.WriteString("\t\"github.com/inipew/goultroid/internal/module\"\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\t%s %q\n", e.alias, e.importPath))
	}
	b.WriteString(")\n\nvar builtinModules = []module.Module{\n")
	for _, e := range entries {
		b.WriteString(fmt.Sprintf("\t%s.Module,\n", e.alias))
	}
	b.WriteString("}\n")

	if err := os.WriteFile("internal/app/generated_modules.go", []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

func discover(root string) ([]entry, error) {
	var result []entry
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || info.Name() != "module.go" {
			return nil
		}
		f, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
		if err != nil {
			return err
		}
		found := false
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.VAR {
				continue
			}
			for _, spec := range gd.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for _, name := range vs.Names {
					if name.Name == "Module" {
						found = true
					}
				}
			}
		}
		if !found {
			return nil
		}
		dir := filepath.ToSlash(filepath.Dir(path))
		result = append(result, entry{alias: filepath.Base(dir), importPath: "github.com/inipew/goultroid/" + dir})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(result, func(i, j int) bool { return result[i].importPath < result[j].importPath })
	return result, nil
}
